# Generated by Django 5.2.3 on 2025-06-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usergoals_user_alter_userinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoals',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
