# Generated by Django 5.1 on 2025-04-20 13:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0006_dprogram_user_alter_workout_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 4, 20, 15, 42, 45, 985505)),
        ),
        migrations.CreateModel(
            name='WorkoutResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2025, 4, 20, 15, 42, 45, 987049))),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WorkoutResult',
                'verbose_name_plural': 'WorkoutResult',
            },
        ),
        migrations.CreateModel(
            name='WorkoutResultSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.IntegerField()),
                ('rep', models.IntegerField()),
                ('weight', models.FloatField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitapp.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitapp.workoutresult')),
            ],
            options={
                'verbose_name': 'WorkoutResultSet',
                'verbose_name_plural': 'WorkoutResultSet',
            },
        ),
    ]
