# Generated by Django 5.1 on 2025-04-20 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0007_alter_workout_date_workoutresult_workoutresultset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 4, 20, 19, 8, 33, 803687)),
        ),
        migrations.AlterField(
            model_name='workoutresult',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 4, 20, 19, 8, 33, 805250)),
        ),
    ]
