# Generated by Django 5.1 on 2025-05-05 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0008_alter_workout_date_alter_workoutresult_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='second_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='third_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 5, 6, 0, 40, 44, 255937)),
        ),
        migrations.AlterField(
            model_name='workoutresult',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 5, 6, 0, 40, 44, 257619)),
        ),
    ]
