# Generated by Django 5.2.1 on 2025-06-05 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0010_alter_exercise_name_alter_workout_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 5, 15, 47, 38, 635800)),
        ),
        migrations.AlterField(
            model_name='workoutresult',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 5, 15, 47, 38, 637425)),
        ),
    ]
