# Generated by Django 5.2.1 on 2025-06-07 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0011_alter_workout_date_alter_workoutresult_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 8, 1, 1, 17, 635159)),
        ),
        migrations.AlterField(
            model_name='workoutresult',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 8, 1, 1, 17, 636640)),
        ),
    ]
