# Generated by Django 5.2.1 on 2025-06-15 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0012_alter_workout_date_alter_workoutresult_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 15, 19, 2, 54, 440306)),
        ),
        migrations.AlterField(
            model_name='workoutresult',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 15, 19, 2, 54, 441781)),
        ),
    ]
