# Generated by Django 5.2.3 on 2025-06-28 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0016_alter_programexercise_weight_alter_workout_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futureworkout',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 29, 0, 52, 54, 737997)),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 29, 0, 52, 54, 731918)),
        ),
        migrations.AlterField(
            model_name='workoutresult',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 29, 0, 52, 54, 736220)),
        ),
    ]
